import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";

const Layout = ({children}) => {
  return (
    <>
      {/* <Head>
        <title>Netflix App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      what is the issue
        <main>{children}</main>
{/* <Header/>
      <Footer/> */}
    </>
  );
};

export default Layout;
