import { useRouter } from "next/router";
import imageUrlBuilder from "@sanity/image-url";
import { client } from "@/utils/client";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";


const slug = ({ sneaker }) => {

  function urlFor(source) {
    return imageUrlBuilder(client).image(source);
  }
  console.log(sneaker);

  return (

    <>
    <Head>
        <title>Shop It | product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      <Header/>
    <article>
      Hello

      {
        !sneaker && 
        <p>Product is loading</p>
      }
      <h1>{sneaker?.slug?.current}</h1>
      <h1>{sneaker?.title}</h1>
      {sneaker?.image && 
      <div className="w-full h-48 sm:w-60 sm:h-60 md:w-80 md:h-80 relative rounded-md overflow-hidden border border-neutral-300">
                <Image
                  src={urlFor(sneaker.image).url()}
                  alt={sneaker.title}
                  fill
                  className="w-full h-full absolute object-cover object-center"
                  />
      </div>
      }
    </article>
    <Footer/>
    </div>

    </>
  );
};

export async function getStaticPaths() {
  const paths = await client.fetch(
    `*[_type == "post" && defined(slug.current)][].slug.current`
  );

  return {
    paths: paths.map((slug) => ({ params: { slug } })),
    fallback: true,
  };
}

export async function getStaticProps(context) {
  const { slug = "" } = context.params;
  const sneaker = await client.fetch(
    `
    *[_type in ["shorts", "sneakers","glasses","watches"] && slug.current == $slug][0]
    `,
    { slug }
    );
    // *[_type == "sneakers" && slug.current == $slug][0]
    
  return {
    props: {
      sneaker,
    },
  };
}

export default slug;