import Head from "next/head";
import { useSession, signOut, getSession } from "next-auth/react";
import Image from "next/image";
import Layout from "@/utils/Layout/Layout";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Body from "@/components/Body";

export default function Home() {
  return (
    <>
    <Head>
        <title>Netflix App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#e3dddd] min-h-screen w-screen">
        <Header/>
        {/* <Body/> */}
        <Footer/>
      </main>
    </>
  );
}
// const { data: session } = useSession()
// const router = useRouter()
// console.log(session);
// const signout = () => {
//   signOut({callbackUrl:"http://localhost:3000/signin"})
// }

{
  /* Signed in as {session.user.name}
  <br />
  <Image src={session.user.image} className='w-20 h-20' width={20} height={20} alt='github image'/>
  <button className="p-2 bg-red-600" onClick={signout}>Sign out</button> */
}
